server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dowon-95/02_cloud-native-spring-in-action
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: /config-repo
